language: ruby

rvm:
- 2.3.1

services:
  - postgresql

before_script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - psql -c 'create database generator_pairs_test;' -U postgres

script: bundle exec rspec

env:
  global:
    secure: ULGG3TrR1G5OIFXrdkJOGEbWObXKDjZQoT7e8HhvEhPn7svyrEdqb9/6rUaJq2P0ZfoneCElfcUaNJruGF8dRW1QJ5oRSMRChwyuOHcw820Lfpq15NeOxhA8yoScCq21ebuEMr/HHaGOrP/FixkrGV1TRfwvxt3n3PnETwHohmuXq74Tjs6pTid+5OjILjqAqp68+aJihFvWNgUwc2hq4Tc4Rk4UomGPTCZg5OeUspRNlBuO0AUUUMUETD5UU/2SmyuAyW3p2FWTuLblwg7C2ql20w+0PcD8rkMnTWUVGBAfZItwpSLju7RTJCf6I8vAoPZX3uMcrJB1yPt6B0nN3tQ506dccO9t3rBsoE+wLJ8X5Sz2OJScLCjk4PfZ3Iar7R4C9lkGZAMdH3hZGAUcw4R5EzKX++32pVHXgEeGEMeuO6il79Zlaz68sUSPa6V994JxY70Nxff8uxP11pgzVi1Y1CEHh3JqcJ6hQf1bj4sHcYM4bitwLltxZHD9xZ9ArKAXXNj2Ivo9+/l4/H3j1s2eMCgW6Ax7/BpTnl6jXkf1Gx6r6SaMg7SiHEiE8cMwel5haGksLF9LDrmlqv4mw1Z8/Up29ZVhMgbZrBRmA+09mTKWIa5RShtrNVIO+bm3TbgQSawfFAwqzOk45lGmpQ21oavkAXTZm6/dtU/eyX0=
